name: Blog
description: >
    Yizhen Li's Blog.

master_repo: false
url: "http://alexandrali3.github.io"
markdown: markdown
highlighter: rouge


plugins: ['jekyll-paginate', 'jekyll-gist', 'jekyll-feed']

paginate: 4

logo:
disqus_shortname:

rtl: false
owner:
  name:           Yizhen Li
  avatar:         "https://avatars1.githubusercontent.com/u/537678?s=240&v=4"
  email:          "1184862561@qq.com"
  # Social networking links used in footer. Update and remove as you like.
  twitter:
  github: https://github.com/alexandrali3
  stackexchange:
  linkedin:
  # For Google Authorship https://plus.google.com/authorship
  google_plus:

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:
