future: true
permalink: /:title/
url: http://alexandrali3.github.io
name: Yizhen Li
author: Yizhen Li
qq: 1184862561
email: 1184862561@qq.com

duoshuo:
beian:
cnzz:
weibo:
github: alexandrali3
about: "这里是 Yizhen Li 的个人博客，创建于 2018 年。"

safe: true
paginate: 20
